services:
  - type: web
      name: splab-frontend
      env: static
      rootDir: frontend
      buildCommand: bun install && bun run build
      staticPublishPath: ./dist
      routes:
      - type: rewrite
        source: /*
        destination: /index.html