# Required GitHub Secrets:
# DOCKERHUB_TOKEN
# KUBE_HOST
# KUBE_TOKEN
# TS_OAUTH_CLIENT_ID
# TS_OAUTH_SECRET
# SERVICE_ACCOUNT_KEY_ENCODED

# Required Github Variables:
# DOCKERHUB_USERNAME
# DOCKERHUB_REPO
# KUBE_DEPLOYMENT_NAME
# KUBE_NAMESPACE


name: backend-cicd
on:
  push:
    branches: cicd

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Add Firebase serviceAccountKey.json
        run: |
          cd backend/app
          echo "${{ secrets.SERVICE_ACCOUNT_KEY_ENCODED }}" > serviceAccountKey_base64.txt
          base64 -d serviceAccountKey_base64.txt > serviceAccountKey.json
          cd ..

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Login to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBE_HOST }}
          k8s-secret: ${{ secrets.KUBE_TOKEN }}

      - name: Update the Deployment Image
        run: |
          kubectl set image deployment/splab-backend splab-backend=$IMAGE_NAME -n splab

