# Required GitHub Secrets:
# DOCKERHUB_TOKEN
# KUBE_HOST
# KUBE_TOKEN

# Required Github Variables:
# DOCKERHUB_USERNAME
# DOCKERHUB_REPO
# KUBE_DEPLOYMENT_NAME
# KUBE_NAMESPACE


name: backend-cicd
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd backend
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest .
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBE_HOST }}
          k8s-secret: ${{ secrets.KUBE_TOKEN }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          namespace: 'splab'
          manifests: |
            k8s/splab.yaml
          images: '${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest'
