# Required GitHub Secrets:
# DOCKERHUB_TOKEN
# KUBE_HOST
# KUBE_TOKEN
# TS_OAUTH_CLIENT_ID
# TS_OAUTH_SECRET

# Required Github Variables:
# DOCKERHUB_USERNAME
# DOCKERHUB_REPO
# KUBE_DEPLOYMENT_NAME
# KUBE_NAMESPACE


name: backend-cicd
on:
  push:
    branches: main

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd backend
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBE_HOST }}
          k8s-secret: ${{ secrets.KUBE_TOKEN }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          namespace: 'splab'
          manifests: |
            k8s/deployment.yaml
          images: '${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest'

      - name: Update the Deployment Image
        run: |
          kubectl set image deployment/splab-backend splab-backend=$IMAGE_NAME

